# A basic container to mine Monero with Nvidia GPUs and ccminer
FROM nvidia/cuda:devel

MAINTAINER bradmccormack100@gmail.com

# Install all pre-req software
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	ca-certificates \
	libssl-dev \
	libcurl4-openssl-dev \
	curl \
	libpthread-stubs0-dev \
	git \
	build-essential \
	automake \
	libgomp1 \
	&& apt-get upgrade -y --no-install-recommends \
# Build the miner
	&& git clone https://github.com/tpruvot/ccminer.git --progress \
	&& cd ccminer \
	&& git checkout linux \
# The provided build script doesn't install ccminer. Install it so we can remove the source
	&& echo "make install" >> /ccminer/build.sh \
	&& ./build.sh \
# Clean up so the image is smaller
	&& rm -rf /ccminer \
	&& apt-get clean \
	&& apt-get remove -y \
	libssl-dev \
	libpthread-stubs0-dev \
	git \
	build-essential \
	automake \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-get autoremove -y

ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:$LD_LIBRARY_PATH

# Expose some environment variables to the container in case you want to interact with them
ENV MONERO_URL stratum+tcp://xmr-usa.dwarfpool.com:8050
ENV MONERO_USER ${MONERO_WALLET_ID}
ENV MONERO_PASS ${MONERO_EMAIL}

# Start up the GPU miner with the correct crypto algorithm - TODO expose more options and allow configuration through environment variables
CMD ccminer --quiet --url=${MONERO_URL} --user=${MONERO_WALLET_ID} --pass=${MONERO_EMAIL} --algo=cryptonight --cpu-priority=0