version: "3"

services:
  cpuminer:
    image:
      servethehome/monero_dwarfpool:zen
    environment:
      - email=${MONERO_EMAIL}
      - username=${MONERO_WALLET_ID}
      - threads=${CPU_LOGICAL_CORE_COUNT}
  gpuminer: 
    build:
      context: .
      dockerfile: dockerfile-nvidia
    environment:
      - MONERO_STRATUM=stratum+tcp://xmr-usa.dwarfpool.com:8050
      - MONERO_USER=${MONERO_WALLET_ID}
      - MONERO_PASS=${MONERO_EMAIL}
    image: bradmccormack/monero:nvidia


